apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  selector:
    app: 1-order-service
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  # clientIP:
  # timeoutSeconds: 10800
  ports:
  - name: order-service
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
