apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1-order-service
  namespace: order
  labels:
    app: 1-order-service
spec:
  selector:
    matchLabels:
      app: 1-order-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: 1-order-service
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', 'until nc -z order-pg-service 5432; do echo waiting for db; sleep 2; done' ]
      containers:
      - name: order-container
        image: "ayushdumasia/order-service:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: PORT
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: DB_PASS
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: order-secrets
              key: DB_PORT
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: order-configmap
              key: KAFKA_BOOTSTRAP_SERVERS
        ports:
        - containerPort: 3000
          name: order-port
      restartPolicy: Always
