apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
spec:
  selector:
    app: 3-payment-service
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  # clientIP:
  # timeoutSeconds: 10800
  ports:
  - name: payment-service
    protocol: TCP
    port: 3002
    targetPort: 3002
    nodePort: 30003
