apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-pg
  namespace: payment
spec:
  serviceName: "payment-pg-service"
  replicas: 2
  selector:
    matchLabels:
      app: payment-pg
  template:
    metadata:
      labels:
        app: payment-pg
    spec:
      containers:
      - name: payment-pg-container
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: payment-pg-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: payment-pg-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: payment-pg-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: payment-pg-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: payment-pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
