apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
  namespace: kafka
  labels:
    app: kafka-ui
data:
  KAFKA_CLUSTERS_0_NAME: "K8 Kafka Cluster"
  KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-service:9092
  # KAFKA_CLUSTERS_0_ZOOKEEPER: crs-zookeeper-0.zookeeper-cluster.kafka.svc.cluster.local:2181
