apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-ui-configmap
              key: KAFKA_CLUSTERS_0_NAME
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-ui-configmap
              key: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
        # - name: KAFKA_CLUSTERS_0_ZOOKEEPER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: kafka-ui-configmap
        #       key: KAFKA_CLUSTERS_0_ZOOKEEPER
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
