apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-server-config
  namespace: pg
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "OrderDB",
          "Group": "Servers",
          "Host": "order-pg-service.order.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "orders",
          "Username": "orderuser",
          "SSLMode": "prefer"
        },
        "2": {
          "Name": "InventoryDB",
          "Group": "Servers",
          "Host": "inventory-pg-service.inventory.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "inventories",
          "Username": "inventoryuser",
          "SSLMode": "prefer"
        },
        "3": {
          "Name": "PaymentDB",
          "Group": "Servers",
          "Host": "payment-pg-service.payment.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "payment",
          "Username": "paymentuser",
          "SSLMode": "prefer"
        }
      }
    }
