apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: inventory
spec:
  selector:
    app: 2-inventory-service
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  # clientIP:
  # timeoutSeconds: 10800
  ports:
  - name: inventory-service
    protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30002
