apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crs-zookeeper
  namespace: kafka
spec:
  replicas: 1
  serviceName: zookeeper-cluster
  selector:
    matchLabels:
      app: zookeeper-cluster
  template:
    metadata:
      labels:
        app: zookeeper-cluster
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - >
                echo $(( $(cat /etc/hosts | grep zookeeper | awk '{print($3)}' | awk '{split($0,array,"-")} END{print array[3]}') + 1 )) > /bitnami/zookeeper/data/myid
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ZOO_SERVERS
          value: crs-zookeeper-0.zookeeper-cluster.kafka.svc.cluster.local:2888:3888
