apiVersion: v1
kind: Service
metadata:
  name: dozzle-service
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: dozzle
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 31007
